lib: plugins: with builtins; ''
package main

// Code generated by Nix. DO NOT EDIT.

import (
	"log"
	${concatStringsSep "\n\t"
		(lib.imap1 (i: p: "p${toString i} \"${p.goPlugin.goModName}\"")
							 plugins)}
)

func init() {
	${concatStringsSep "\n\t"
		(lib.imap1
		 (i: p: "plugins = append(plugins, p${toString i}.Plugin())")
		 plugins)}
	log.Println("plugins have been initialized.")
} 
''